# Generated by Django 4.0.5 on 2022-06-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Audience',
        ),
    ]
