# Generated by Django 4.0.5 on 2022-06-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0002_rename_group_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='message_api.audience'),
        ),
    ]
